# Generated by Django 3.0.8 on 2020-07-05 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cusomer',
            new_name='Customer',
        ),
    ]
