# Generated by Django 3.0.8 on 2020-07-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200705_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
